### ISSUE TITLE
Subtypes in @traitdef

### ISSUE THREAD

**Issue by mindbound** [mauro3/Traits.jl#2]
How would one write correctly e.g. the following,
```julia
@traitdef Foo{X} begin
    fnx{Y <: Integer}(X, Y) -> Integer
end
```
i.e. so that `Y` can only be a subtype of `Integer`? I assume it would require a combination of associated types and `@constraint`s but I can't seem to figure out the details from the documentation. TIA.

**Comment by mauro3** [comment]
The original example in this issue works, actually for quite a while now, since 92b0b376. So closing.

**Comment by mindbound** [comment]
Thank you, very glad to see this fixed/implemented.

**Comment by mauro3** [comment]
Sorry, I was wrong!  Whilst it is no error to define:
```julia
@traitdef Foo{X} begin
    fnx{Y <: Integer}(X, Y) -> Integer
end
```
it doesn't work:
```
julia> fnx{Y<:Integer}(x::Int, y::Y) = 1
fnx (generic function with 1 method)

julia> istrait(Foo{Int}, verbose=true)
Method fnx with call signature (Int64,Y<:Integer) not defined for Foo{Int64}
false
```
because `method_exists` doesn't work with `TypeVar`s:  https://github.com/JuliaLang/julia/issues/9043

This is in fact what I wrote above but for some reason I thought it was fixed after all. Sorry, I'm just getting up to speed with this again and was a bit confused...

**Comment by mauro3** [comment]
@mindbound now it is fixed. I replaced all `method_exists` checks with hand-rolled code.

**Comment by mindbound** [comment]
Thank you. This is a great addition to Julia, especially coming from a Haskell-ish background.

**Comment by mauro3** [comment]
Thanks a lot!  Let me know if you find other missing bits or have other comments.
